export const quotes = {
    stressed: [
        "You don’t have to control your thoughts. You just have to stop letting them control you.",
        "Take a deep breath. You've got this.",
        "Don't stress. Do your best and forget the rest.",
        "Stress is caused by being ‘here’ but wanting to be ‘there.’",
        "It’s okay to slow down. Rest is productive too.",
        "Breathe in calm. Breathe out tension.",
        "Your peace is more important than their opinion.",
        "You’re doing better than you think you are.",
        "You don’t need to have all the answers right now.",
        "This moment will pass — and you’ll rise stronger.",
        "You are enough, exactly as you are — no improvements needed ",
        "Your presence matters more than you know. The world is better with you in it 🌍💫",
        "You are not a burden — you are a light learning how to shine 🌟",
        "Someone out there smiles because you exist 😊",
        "You’ve come so far — don’t forget to look back and see how strong you’ve been 💪",
        "You are allowed to be both a masterpiece and a work in progress 🎨",
        "You are not too much. You are exactly what someone needs 🫂",
        "Your happiness is not selfish. It’s a gift to the people who love you 🎁",
        "You don’t need to earn rest, love, or joy — they are your birthright 🌿",
        "The way you show up, even when it’s hard, is incredibly brave 💖",
        "You bring value simply by being here 🧘",
        "Your thoughts matter. Your feelings are valid. You are real. You are loved 💌",
        "Every time you’ve felt like giving up, you didn’t. That matters 🛤️",
        "Even on your worst day, you are still worthy of love, peace, and joy 🌈",
        "You are not falling behind — life is not a race 🐢❤️",
        "It’s okay to take up space. You belong here 🪐",
        "You were never meant to be perfect. You were meant to be real 💬",
        "Your kindness has already changed someone’s life — even if you don’t realize it 💫",
        "There’s no one else in the universe exactly like you — and that’s powerful 🌟",
        "Healing is not linear. It’s okay to wobble. What matters is you keep going 🌀"
    ],
    anxious: [
      "You are a beautiful work in progress — be kind to your becoming.",
      "Smile. Breathe. Shine. You were made for this moment.",
      "You don’t need to rush. The sun still rises slowly every day.",
      "Your heart knows the way. Trust it a little more today.",
      "There’s magic in your every breath — slow down and feel it.",
      "Joy doesn’t need a reason — let yourself feel it anyway.",
      "You are exactly where you need to be. Breathe into it.",
      "You radiate light, even when you can’t see it yourself.",
      "Speak to yourself like someone you love — because you are.",
      "Let your inner peace be louder than your doubts.",
      "Every small step forward is a celebration of your strength.",
      "You don’t have to be perfect to be deeply worthy.",
      "You carry calm inside you — take a moment to return to it.",
      "The world is better with your smile in it. Keep showing up.",
      "Love yourself like it’s your superpower — because it is.",
      "Your glow comes from within — protect it, fuel it, trust it.",
      "Rest is not a weakness. It’s how you grow your wings.",
      "You’re not behind. You’re blooming on your own timeline.",
      "Grace is doing your best with what you have, where you are.",
      "You deserve peace, even on days you don’t feel strong.",
      "Celebrate yourself — you’ve come further than you think.",
      "Progress is quiet. Trust what’s happening beneath the surface.",
      "Being soft with yourself is a form of strength.",
      "You’re more than enough — exactly as you are right now.",
      "Your journey is unfolding beautifully — trust the process.",
      "Let today be lighter. Let yourself feel joy without guilt.",
      "There’s no one like you — and that’s your power.",
      "You are a soul full of sunshine, even on cloudy days.",
      "Breathe in calm. Breathe out comparison.",
      "Keep going. The gentle version of you is still powerful."
    ],
    tired: [
      "Rest is not a reward. It's a right.",
      "It’s okay to do nothing sometimes. That’s how you heal.",
      "You don’t need to earn your rest — you deserve it.",
      "Recharge. You cannot pour from an empty cup.",
      "Even machines need to power down. So can you.",
      "Sleep doesn’t mean weakness. It means wisdom.",
      "Gentle reminder: your body needs care too.",
      "You’ve done enough for today. Be proud of that.",
      "Slow progress is still progress.",
      "You’re allowed to pause. Life isn’t a race.",
      "It's okay to rest. Even the stars need the night.",
      "You don’t have to do it all today. You just have to breathe.",
      "Rest is not quitting. It’s preparing.",
      "You’re allowed to slow down — your worth isn’t measured in hustle.",
      "Even when you're tired, you're still moving forward.",
      "Some days are for progress. Some are just for survival. Both count.",
      "Rest, not because you are weak, but because you are wise.",
      "Your energy is sacred. Spend it gently.",
      "You’re tired because you’re trying. Be proud of that.",
      "Nothing blooms all year. Take your season of rest.",
      "Doing your best looks different every day — and that’s okay.",
      "You are not lazy. You are healing, growing, and existing.",
      "Let your body and soul catch up with your dreams.",
      "It’s brave to pause. It’s brave to say ‘not right now.’",
      "You’re allowed to be a masterpiece and a work-in-progress at once.",
      "Fatigue is not failure. It's a whisper from your body to breathe.",
      "Sometimes the strongest thing you can do is rest.",
      "Progress doesn’t disappear just because you’re tired.",
      "Take a deep breath — rest is a form of resistance too.",
      "Let go of the guilt. You’re human, not a machine.",
      "You’ve carried so much — it’s okay to put it down for a while.",
      "Sleep. Hydrate. Stretch. Your sparkle will return.",
      "Not every day has to be productive. Some just have to be gentle.",
      "Even in rest, your soul is growing strong roots.",
      "Honor your tired self — it has done so much.",
      "You can do hard things, but not all at once. Rest in between.",
      "Be soft with yourself. You're doing better than you think.",
      "Resting is part of the rhythm. Don’t skip the quiet parts.",
      "A tired mind still holds bright ideas — let them rest too.",
      "One pause does not erase the path — it prepares you for more."
    ],
    overwhelmed: [
      "Just breathe. One thing at a time. You got this 💪",
      "Overwhelmed is a sign it’s time to slow down, not give up.",
      "Small steps still lead to big changes.",
      "You’re juggling so much — it’s okay to set something down.",
      "You don’t need to figure it all out today.",
      "Do the next right thing, not everything.",
      "Let go of what you can't control, and focus on what you can.",
      "It's okay to ask for help. You’re not meant to carry it all alone.",
      "Take a deep breath. You’ve survived every hard day before.",
      "Break the mountain into pebbles, and move one at a time.",
      "Smile. You deserve this joy 😊",
      "The sun is shining and so are you ☀️",
      "Enjoy the moment — it’s yours.",
      "Your happiness lights up more than just your day.",
      "You’re doing amazing. Keep that energy 💃",
      "Soak up this good feeling and let it grow.",
      "You earned this smile — wear it proudly.",
      "Let happiness spill over into everything you do.",
      "Your light makes a difference 🌟",
      "Gratitude turns what we have into enough ❤️",
    ],
    
  };
  