export const quotes = {
    stressed: [
      "You don’t have to control your thoughts. You just have to stop letting them control you.",
      "Take a deep breath. You've got this.",
      "Don't stress. Do your best and forget the rest.",
      "Stress is caused by being ‘here’ but wanting to be ‘there.’",
      "It’s okay to slow down. Rest is productive too.",
      "Breathe in calm. Breathe out tension.",
      "Your peace is more important than their opinion.",
      "You’re doing better than you think you are.",
      "You don’t need to have all the answers right now.",
      "This moment will pass — and you’ll rise stronger.",
      "You are enough, exactly as you are — no improvements needed ",
        "Your presence matters more than you know. The world is better with you in it 🌍💫",
        "You are not a burden — you are a light learning how to shine 🌟",
        "Someone out there smiles because you exist 😊",
        "You’ve come so far — don’t forget to look back and see how strong you’ve been 💪",
        "You are allowed to be both a masterpiece and a work in progress 🎨",
        "You are not too much. You are exactly what someone needs 🫂",
        "Your happiness is not selfish. It’s a gift to the people who love you 🎁",
        "You don’t need to earn rest, love, or joy — they are your birthright 🌿",
        "The way you show up, even when it’s hard, is incredibly brave 💖",
        "You bring value simply by being here 🧘",
        "Your thoughts matter. Your feelings are valid. You are real. You are loved 💌",
        "Every time you’ve felt like giving up, you didn’t. That matters 🛤️",
        "Even on your worst day, you are still worthy of love, peace, and joy 🌈",
        "You are not falling behind — life is not a race 🐢❤️",
        "It’s okay to take up space. You belong here 🪐",
        "You were never meant to be perfect. You were meant to be real 💬",
        "Your kindness has already changed someone’s life — even if you don’t realize it 💫",
        "There’s no one else in the universe exactly like you — and that’s powerful 🌟",
        "Healing is not linear. It’s okay to wobble. What matters is you keep going 🌀"
    ],
    anxious: [
      "Breathe. You are enough. You are capable. You've got this.",
      "Anxiety is like a rocking chair. It gives you something to do, but it gets you nowhere.",
      "It’s okay to take a step back. You don’t have to do everything all at once.",
      "Feelings are not facts. Just because you feel worried doesn't mean you are in danger.",
      "You have survived 100% of your anxious thoughts so far.",
      "Peace begins with a single breath.",
      "You are safe. You are grounded. You are here.",
      "Your worry does not define your worth.",
      "Repeat after me: I am okay. I am calm. I am in control.",
      "Anxiety is loud, but your strength is louder.",
    ],
    tired: [
      "Rest is not a reward. It's a right.",
      "It’s okay to do nothing sometimes. That’s how you heal.",
      "You don’t need to earn your rest — you deserve it.",
      "Recharge. You cannot pour from an empty cup.",
      "Even machines need to power down. So can you.",
      "Sleep doesn’t mean weakness. It means wisdom.",
      "Gentle reminder: your body needs care too.",
      "You’ve done enough for today. Be proud of that.",
      "Slow progress is still progress.",
      "You’re allowed to pause. Life isn’t a race.",
    ],
    overwhelmed: [
      "Just breathe. One thing at a time. You got this 💪",
      "Overwhelmed is a sign it’s time to slow down, not give up.",
      "Small steps still lead to big changes.",
      "You’re juggling so much — it’s okay to set something down.",
      "You don’t need to figure it all out today.",
      "Do the next right thing, not everything.",
      "Let go of what you can't control, and focus on what you can.",
      "It's okay to ask for help. You’re not meant to carry it all alone.",
      "Take a deep breath. You’ve survived every hard day before.",
      "Break the mountain into pebbles, and move one at a time.",
    ],
    happy: [
      "Smile. You deserve this joy 😊",
      "The sun is shining and so are you ☀️",
      "Enjoy the moment — it’s yours.",
      "Your happiness lights up more than just your day.",
      "You’re doing amazing. Keep that energy 💃",
      "Soak up this good feeling and let it grow.",
      "You earned this smile — wear it proudly.",
      "Let happiness spill over into everything you do.",
      "Your light makes a difference 🌟",
      "Gratitude turns what we have into enough ❤️",
    ]
  };
  